### PR TITLE
267 improve submission process for editors

### LINKED ISSUE #267: Improve Submission Process for Editors
- Harus ada minimal satu editor untuk menerima dan melanjutkan proses pada submission.
- Jika User dengan Role Editor menerima submission, maka editor tersebut otomatis ter-assign ke submission tersebut.
- Jika semua editor dihapus, maka submission tidak dapat dilanjutkan sampai ada editor yang ditugaskan.
- Editor masih dapat melakukan input dan edit pada stage sebelumnya yang sudah selesai.
- Terdapat fitur reviewer dan penulis anonim saat melakukan review yang dibuat oleh Editor.

### PR DESCRIPTION
**Pull request by faisalwahyudi10**
- [x]  Validation for submission acceptance must include at least one assigned editor
- [x]  Editors can accept or decline submissions. If accepted, the editor is automatically assigned to the submission
- [x]  If all editors are unassigned, the submission cannot proceed
- [x]  Fix Bug Select Reviewer
- [x] Fix bug Review page accessible with pending reviewer status
- [x] Fix Bug Review Page can access by another user
- [x]  Can edit data from previous stages

Testing List untuk Edit data ftom Previous Stages
https://docs.google.com/document/d/1OFnV-Vi2ij-KAy095TPKymliDw_cfSGOjD1j3a_NpLs/edit?usp=sharing

### CODE REVIEW

**Comment by rahmanramsi** [comment]
Seharusnya assign notification cuman tampil untuk role yg bisa mengassign editor, untuk role lain tidak perlu ditampilkan, atau tampilkan notifikasi lain seperti Editor belum diassign untuk submission ini

CleanShot 2024-06-06 at 15 01 33

**Comment by rahmanramsi** [comment]
Tidak ada tombol cancel saat ingin change decision

https://github.com/OpenSynergic/leconfe/assets/48276043/e81ea454-e43c-4357-96a0-fc012b48bc00

**Comment by rahmanramsi** [comment]
Beda workflow tetapi malah sama statusnya Submission accepted for review.

CleanShot 2024-06-06 at 15 27 49


CleanShot 2024-06-06 at 15 27 16

**Comment by rahmanramsi** [comment]
Sewaktu review sudah di accept, namun ada perubahan decision menjadi meminta revisi. Tahapan status nya masih Editing, seharusnya berubah kembali menjadi On Review

CleanShot 2024-06-06 at 15 41 24

**Comment by faisalwahyudi10** [comment]
Task List :

- [x] Fix Assign Editor Notification
- [x] Add Cancel Button when trying Change Decision
- [x] Fix Label for submission accepted
- [x] Fix Request Revision Logic

**Comment by faisalwahyudi10** [comment]
**Fix Assign Editor Notification**

[Screencast from 2024-06-06 16-50-34.webm](https://github.com/OpenSynergic/leconfe/assets/121210620/46ea43c1-be42-4e93-b770-8c4682840b75)

**Add Cancel Button when trying Change Decision and Fix Label for submission accepted**

[Screencast from 2024-06-06 16-52-35.webm](https://github.com/OpenSynergic/leconfe/assets/121210620/b9e04bbd-b4e8-48da-9ecf-24ae8d03e4ba)

 **Fix Request Revision Logic**

[Screencast from 2024-06-06 16-53-43.webm](https://github.com/OpenSynergic/leconfe/assets/121210620/f6f1bf0f-7ab4-42ea-8c48-ecd118e776c8)

**Review by rahmanramsi — APPROVED** [review]

**Pull request merged**
